require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'gyanbooster' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  target 'gyanboosterTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'gyanbooster-tvOS' do
  # Pods for gyanbooster-tvOS

  target 'gyanbooster-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
