export const FETCHING_QUESTION_REQUEST = 'FETCHING_PEOPLE_REQUEST';
export const FETCHING_QUESTION_SUCCESS ='FETCHING_QUESTION_SUCCESS';
export const FETCHING_QUESTION_FAILURE ='FETCHING_QUESTION_FAILURE';
